### ISSUE TITLE
Usecase diagramm készítése

### ISSUE THREAD

**Issue by ChrisThe0ne** [szunyix/5_csoport#1]
### Camping Receptioninst
A camping needs an online system where reservations can be managed. The
camping sells camping slots where the guests can set their tents. A camping
slot can be given to a single tent or caravan with car. Electricity is optionally
sold for camping slots. The camping wants to know which camping slot is
occupied currently or reserved. In additon the receptioninst should query the
open slots in a fixed interval. A slot is open if it is not occupied any time during
the given period. Finally, the system should generate and invoice when the
guests are leaving.
Visualization is a key element of the Camping Receptioninst site. The re-
ceptionins wants to see the layout of the camping site in the monitor.

- [x]  Írj usecase diagrammot a vízió alapján

AC

- plantUML file a docs mappában

**Comment by J3d4-zz** [comment]
Megcsinaltam a UML doksit, es fel is toltottem sajat branchba, ha kell majd mergelitek masterbe, de gondoltam szokni kene hogy ne mindent oda toljunk. Zarom az issuet.
