### ISSUE TITLE
Cella_adat_Controller + DTO (backend)

### ISSUE THREAD

**Issue by szunyix** [szunyix/5_csoport#9]
Cellainformációs ablak adatai SRS dokumentum alapján. 

AC: DTO és Controller állományok

**Comment by J3d4-zz** [comment]
Atalakitottam a cella controllert es mergeltem minden mukodo dolgot masterba. (cellanak eleg egy id meg allapot, relacios adatbazisba ugy is referalni fogja a foglalas a cellaId-t)
